// frontend/src/TagView.tsx
import { useMemo, useState } from 'react'
import type { TagNode } from './tagTypes'

type Props = {
  node: TagNode
  depth: number
  collapsedIds: Set<string>
  onToggleCollapse: (id: string) => void
  onDataChange: (id: string, data: string) => void
  onNameChange: (id: string, name: string) => void
  onAddChild: (id: string) => void
}

export function TagView({
  node,
  depth,
  collapsedIds,
  onToggleCollapse,
  onDataChange,
  onNameChange,
  onAddChild,
}: Props) {
  const isCollapsed = collapsedIds.has(node.id)
  const hasChildren = (node.children?.length ?? 0) > 0

  const indentStyle = useMemo(() => ({ paddingLeft: `${depth * 16}px` }), [depth])
  const [isRenaming, setIsRenaming] = useState(false)
  const [draftName, setDraftName] = useState(node.name)

  return (
    <div className="tag" style={indentStyle}>
      <div className="tagHeader">
        <button
          type="button"
          className="collapseBtn"
          onClick={() => onToggleCollapse(node.id)}
          aria-label={isCollapsed ? 'Expand' : 'Collapse'}
        >
          {isCollapsed ? '>' : 'v'}
        </button>
        {isRenaming ? (
          <input
            className="nameInput"
            value={draftName}
            autoFocus
            onChange={(e) => setDraftName(e.target.value)}
            onBlur={() => setIsRenaming(false)}
            onKeyDown={(e) => {
              if (e.key === 'Enter') {
                const next = draftName.trim()
                if (next.length > 0) onNameChange(node.id, next)
                setIsRenaming(false)
              }
              if (e.key === 'Escape') {
                setDraftName(node.name)
                setIsRenaming(false)
              }
            }}
          />
        ) : (
          <button
            type="button"
            className="tagName"
            title="Click to rename"
            onClick={() => {
              setDraftName(node.name)
              setIsRenaming(true)
            }}
          >
            {node.name}
          </button>
        )}
        <button type="button" className="addChildBtn" onClick={() => onAddChild(node.id)}>
          Add Child
        </button>
      </div>

      {!isCollapsed && (
        <div className="tagBody">
          {hasChildren ? (
            <div className="children">
              {node.children!.map((c) => (
                <TagView
                  key={c.id}
                  node={c}
                  depth={depth + 1}
                  collapsedIds={collapsedIds}
                  onToggleCollapse={onToggleCollapse}
                  onDataChange={onDataChange}
                  onNameChange={onNameChange}
                  onAddChild={onAddChild}
                />
              ))}
            </div>
          ) : (
            <label className="dataRow">
              <span className="dataLabel">Data</span>
              <input
                className="dataInput"
                value={node.data ?? ''}
                onChange={(e) => onDataChange(node.id, e.target.value)}
              />
            </label>
          )}
        </div>
      )}
    </div>
  )
}

// frontend/src/components/TagView.vue
<script setup lang="ts">
import { computed, ref, watch } from 'vue'
import type { TagNode } from '../tagTypes'
import TagViewItem from './TagView.vue'

const props = defineProps<{
  node: TagNode
  depth: number
  collapsedIds: Set<string>
}>()

const emit = defineEmits<{
  toggleCollapse: [id: string]
  dataChange: [id: string, data: string]
  nameChange: [id: string, name: string]
  addChild: [id: string]
}>()

const isCollapsed = computed(() => props.collapsedIds.has(props.node.id))
const hasChildren = computed(() => (props.node.children?.length ?? 0) > 0)
const indentStyle = computed(() => ({ paddingLeft: `${props.depth * 16}px` }))

const isRenaming = ref(false)
const draftName = ref(props.node.name)

watch(
  () => props.node.name,
  (n) => {
    if (!isRenaming.value) draftName.value = n
  },
)

function onNameKeydown(e: KeyboardEvent) {
  if (e.key === 'Enter') {
    const next = draftName.value.trim()
    if (next.length > 0) emit('nameChange', props.node.id, next)
    isRenaming.value = false
  }
  if (e.key === 'Escape') {
    draftName.value = props.node.name
    isRenaming.value = false
  }
}
</script>

<template>
  <div class="tag" :style="indentStyle">
    <div class="tagHeader">
      <button
        type="button"
        class="collapseBtn"
        :aria-label="isCollapsed ? 'Expand' : 'Collapse'"
        @click="emit('toggleCollapse', node.id)"
      >
        {{ isCollapsed ? '>' : 'v' }}
      </button>
      <input
        v-if="isRenaming"
        v-model="draftName"
        class="nameInput"
        autofocus
        @blur="isRenaming = false"
        @keydown="onNameKeydown"
      />
      <button
        v-else
        type="button"
        class="tagName"
        title="Click to rename"
        @click="
          draftName = node.name;
          isRenaming = true
        "
      >
        {{ node.name }}
      </button>
      <button type="button" class="addChildBtn" @click="emit('addChild', node.id)">Add Child</button>
    </div>

    <div v-if="!isCollapsed" class="tagBody">
      <div v-if="hasChildren" class="children">
        <TagViewItem
          v-for="c in node.children"
          :key="c.id"
          :node="c"
          :depth="depth + 1"
          :collapsed-ids="collapsedIds"
          @toggle-collapse="(id: string) => emit('toggleCollapse', id)"
          @data-change="(id: string, data: string) => emit('dataChange', id, data)"
          @name-change="(id: string, name: string) => emit('nameChange', id, name)"
          @add-child="(id: string) => emit('addChild', id)"
        />
      </div>
      <label v-else class="dataRow">
        <span class="dataLabel">Data</span>
        <input
          class="dataInput"
          :value="node.data ?? ''"
          @input="emit('dataChange', node.id, ($event.target as HTMLInputElement).value)"
        />
      </label>
    </div>
  </div>
</template>
